browser=chrome
headless=false
baseUrl=https://practicesoftwaretesting.com
api.base.url=https://api.practicesoftwaretesting.com
admin.email=admin@practicesoftwaretesting.com
admin.password=welcome01
default.customer.email=customer@practicesoftwaretesting.com
default.customer.password=welcome01
